### ISSUE TITLE
Can't Scroll while using Diz

### ISSUE THREAD

**Issue by Mancosiris13** [lewhunt/divz#1]
I imported and used the library into my website but I cant scroll up or down, it simply freezes the page

**Comment by lewhunt** [comment]
Hi,

Thanks for trying it out!

Hiding the page scrollbar was done by design because Divz is intended to be a 'fullscreen' experience that can use vertical scroll/swipes for the 3D navigation between its child div items. If you use Divz in a page that scrolls, then page scrolling will trigger the Divz navigation and vice versa.

However I realise there may be some limited use cases, so I have released a small update in v1.1.6 with a new prop called **isScrollPageEnabled** that you can set to true to override the default behaviour.

```<Divz isScrollPageEnabled={true}>```

Cheers,
Lewis
